version: '2'
services:
  postgis:
    image: mdillon/postgis:9.5
    ports:
      - "54321:5432"

  elasticsearch:
    image: elasticsearch:5.2.0
    environment:
      - bootstrap.memory_lock=true
      - thread_pool.search.queue_size=10000
      - node.max_local_storage_nodes=20
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 6g
    ports:
      - 9200:9200

  geocoder:
    build: .
    depends_on:
      - postgis
      - elasticsearch
    volumes:
      - .:/usr/src/app
    env_file: .env

  # loader:
  #   build: ./grasshopper-loader
  #   links:
  #     - elasticsearch
  #   volumes:
  #     - ./grasshopper-loader/test/data:/usr/src/app/test/data/
