version: '2'
services:
  elasticsearch:
    image: elasticsearch:5.2.0
    environment:
      - bootstrap.memory_lock=true
      - thread_pool.search.queue_size=10000
      - node.max_local_storage_nodes=20
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 6g
    ports:
      - 9200:9200

  geocoder:
    build: ./geocoder
    depends_on:
      - elasticsearch
    volumes:
      - ./geocoder:/usr/src/app
    entrypoint:
      - python
    env_file: .env
